name: procrastinator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  uuid: ^4.5.0
  shared_preferences: ^2.5.4
  provider: ^6.1.2
  table_calendar: ^3.1.0
  intl: ^0.19.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  record: 5.1.0 
  path_provider: ^2.1.2
  home_widget: ^0.7.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  envied: ^0.5.4+1
  analyzer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.5.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.8

dependency_overrides:
  record_platform_interface: 1.1.0

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2A2A4A" 
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true